### ISSUE TITLE
ftpm kernel wrapper driver getting OPTEE out of memory error when invoking tee_client_open_session

### ISSUE THREAD

**Issue by maskimthedog** [jonmason/meta-arm#1]
I am working with imx8mm based system and am geting OPTEE out of memory error when the ftpm kernel wrapper driver invokes tee_client_open_session on probe.  Any ideas?

tee_client_open_session failedftpm_tee_probe: tee_client_open_ses
sion failed, err=ffff000c

**Comment by jonmason** [comment]
Not sure if this issue was ever resolved.  We don't use GitHub issues.  Please send email to meta-arm@lists.yoctoproject.org if the issue still exists
