### ISSUE TITLE
On enabling RSA_4096, ftpm as a TA panicked with TEEC_ERROR_BAD_STATE(0xffff0007)

### ISSUE THREAD

**Issue by kuldeepmarker-eaton** [jonmason/meta-arm#2]
HI All, 

I want to use RSA with 4096 bits size and in order to do that I defined the RSA_4096 in optee-ftpm_git.bb recipe file. The recipe builds successfully and when I try to run this command I am getting response TEEC_ERROR_BAD_STATE(0xffff0007).
tpm2_createprimary -Grsa2048:aes128cfb -C o -c parent.ctx

If I just use the default size of 2048 and 1024 bits size the command runs successfully. So am I missing anything here to enable RSA with other sizes as supported by TPM. 
I have just added this line in recipe file to enable RSA with 4096 bits size.
CFLAGS += "-DRSA_16384 -DRSA_3072 -DRSA_4096"

**Comment by jonmason** [comment]
Not sure if this issue was ever resolved.  We don't use GitHub issues.  Please send email to meta-arm@lists.yoctoproject.org if the issue still exists
